### ISSUE TITLE
JustFlight PA28R Arrow III, v0.3.0 Landing gear actions not recorded

### ISSUE THREAD

**Issue by jctarvin** [nguyenquyhy/Flight-Recorder#68] opened 2021-03-29 22:23 UTC
This has worked before on other aircraft, even the Arrow III. This time it did not record raising the gear. Made rest of flight not very realistic. Oops!

Nonetheless, I love the program!!

**Comment by nguyenquyhy** [comment] 2021-03-29 23:02
Yes I notice this issue with several 3rd party aircraft after their own recent update. I'm not sure what's going on yet. I believe if you try to export the recording into CSV and open it in Excel, you should see that the `GearHandlePosition` shows correct values (0 for up and 1 for down).

I feel like for some reason many 3rd aircraft change the way they handle gear event from SimConnect, but I'm not too sure. I'll look into this more this week.

**Comment by jctarvin** [comment] 2021-03-30 01:35
Thank you, Nguyen!!

I'll try it with the Carenado Mooney tomorrow. Pretty sure that aircraft has worked just fine. 

And, thank you for a wonderful addition to MSFS2020!

⁣John​


-------- Original Message --------

**Comment by nguyenquyhy** [comment] 2021-03-30 04:13
Have you updated the Arrow to version 0.3.0? I just tested and it seems to work fine. I know that they fixed some issue regarding external input before so that maybe the cause.

**Comment by jctarvin** [comment] 2021-03-30 16:33
Yes, I have v0.3.0 for the Arrow III.

However, I just noticed I'm running v0.8 of  Flight Recorder instead of v0.9. Will update and try again.

Thank you so much for your help!!

⁣John​


-------- Original Message --------

**Comment by nguyenquyhy** [comment] 2021-03-31 17:46
Oh the latest version of Flight Recorder is 0.11.1, so you might want to try that one instead.

**Comment by jctarvin** [comment] 2021-03-31 22:00
I changed to Carenado Mooney and updated Flight Recorder to v0.11.1.0 and darned if I didn't have same landing gear issues. I posted that on github.

A few moments ago I made my same flight with current Arrow III v.0.3 and Flight Recorder v0.11.1.0 and it worked just fine. No issues.

Thanks!! (And thanks for your patience with me!!)

⁣John​


-------- Original Message --------

**Comment by jctarvin** [comment] 2021-04-01 04:10
Nguyen,

Happy to report that Arrow III seems to be working fine with Flight Recorder v0.11.1.0

⁣John​

**Comment by nguyenquyhy** [comment] 2021-04-06 06:24
I just notice one scenario where you can find the gear not going up.

1. Turn on State Saving
2. Finish a flight with all electricity turned off (BAT and ALT) and go back to main menu
3. Start a new flight on the runway (or reset the flight if it was started on runway). The aircraft is now with engine running but electricity off.
4. Start a replay. The gear handles will move correctly, but gears won't go up due to lack of electricity.

**Comment by nguyenquyhy** [comment] 2021-04-09 17:30
I'll close this for now. Please feel free to reopen if this happens in other scenarios.

**Closed by nguyenquyhy** 2021-04-09 17:30 UTC
Labels: bug, pending-information
